import Head from "next/head"
import { useRouter } from "next/router"
import { useState, useEffect} from "react"
import Image from "next/image"

export default function Id() {
    const router = useRouter()
    const { id_course } = router.query
    const [course, setCourse] = useState([])
    const [coverUrl, setCoverUrl] = useState("")
   
    function goIndex() {
        router.push("/")
    }

    useEffect(() => {
        if (!id_course) {
            return
        }
        var url = "/api/courses/getCourse?id_course=" + id_course
        fetch(url)
          .then(response => response.json())
          .then(data => setCourse(data.course))
    }, [id_course])
    return (
        <>
            <Head>
                <title>Kualify</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/kualify_logo.png" />
            </Head>
            <main>
                
                <a className="text-3xl font-bold">{course.title}</a>
                <div className="w-2/3 p-10">
                    {course.tags?.map(item => (
                        <a key={item}>
                            <div className="inline-block pr-4 pb-4">
                                <p className="tag" >{item}</p>
                            </div>
                        </a>
                    ))}
                </div>
                <img className="bg-gray-200" height="300" width="600" alt="Course Cover"></img>

            </main>
        </>
    )
}

