import Head from "next/head"
import Router, { useRouter } from "next/router"
import { useState, useEffect, Fragment} from "react"
import Image from "next/image"
import axios from "axios"
import YouTube from 'react-youtube'
import { Dialog, Transition } from '@headlessui/react'
import Navbar from '@/components/Navbar'

export default function Id() {
    const router = useRouter()
    const { id_course } = router.query
    const [course, setCourse] = useState({})
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")
    const [activeStep, setActiveStep] = useState(0)
    const [isOpen, setIsOpen] = useState(false)
    const [videoKey, setVideoKey] = useState("")
    const courseLenght = course && course.steps && course.steps.length
    

    const videoOpts = {
        playerVars: {
          start: course && course.steps && course.steps[activeStep] && course.steps[activeStep].video.start_time, 
          end: course && course.steps && course.steps[activeStep] && course.steps[activeStep].video.end_time,
          controls: 0,
          showinfo: 0,
          rel: 0,
          disablekb: 1,
          iv_load_policy: 0,
          modestbranding: 1,
          showinfo: 0 
        },
      };

    function nextStep() {
        setActiveStep(activeStep + 1)
        setIsOpen(false)
        setVideoKey(videoKey + 1)
    }

    function goIndex() {
        router.push("/")
    }

    const handleGetUser = async () => {  
        const credentials = { email, password } 
        const user = await axios.post("/api/auth/checkAuth", credentials)
        console.log(email)
        if (user.data.message == "Cookie not found") {
          Router.push("/login")
        }
    }

    useEffect(() => {
        if (!id_course) {
            return
        }
        var url = "/api/courses/getCourse?id_course=" + id_course
        fetch(url)
          .then(response => response.json())
          .then(data => setCourse(data.course))
    }, [id_course])

    useEffect(() => {
        handleGetUser()
    }, [])

    useEffect(() => {
        if ((activeStep +1) > courseLenght) {
            router.push(`/${id_course}/outro`)
        }}, [activeStep])
    
    function closeModal() {
        setIsOpen(false)
      }
    
      function openModal() {
        setIsOpen(true)
      }
    return (
        <>
            <Head>
                <title>Kualify</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/icon.png" />
            </Head>    
            <main className="text-center">
                <Navbar />
                <div className="justify-center">
                    <div className="pl-10 pr-10 pb-6">
                        {course.tags?.map(item => (
                            <a key={item}>
                               <div className="inline-block pb-4 text-gray-800">
                                  <p className="font-semibold py-1.5 px-6 badge rounded-md bg-[#1A1C1F] cursor-pointer text-white">{item}</p>
                                </div>
                            </a>))} 
                        <h2 className="text-4xl font-bold content-center text-gray-800">{course.title}</h2>
                        <h2 className="text-xl text-gray-800 font-semibold pt-4">{activeStep + 1}. {course && course.steps && course.steps[activeStep] && course.steps[activeStep].title}</h2>
                    </div>
                    <div className="justify-center p-6 flex md:gap-8">
                        <div className="rounded-lg overflow-hidden md:w-max shadow-md">
                            <YouTube key={videoKey} opts={videoOpts} videoId={course && course.steps && course.steps[activeStep] && course.steps[activeStep].video.url}/>
                        </div>
                    </div>
                    <div className="pb-16 pt-6">
                        <button className="bg-[#1A1C1F] text-white w-96 py-3 rounded-md hover:bg-[#2C3036] font-bold shadow-md" onClick={openModal}>Continuar</button>
                    </div>
                        <Transition appear show={isOpen} as={Fragment}>
                            <Dialog as="div" className="relative z-10" onClose={closeModal}>
                            <Transition.Child
                                as={Fragment}
                                enter="ease-out duration-300"
                                enterFrom="opacity-0"
                                enterTo="opacity-100"
                                leave="ease-in duration-200"
                                leaveFrom="opacity-100"
                                leaveTo="opacity-0"
                            >
                                <div className="fixed inset-0 bg-black bg-opacity-25" />
                            </Transition.Child>

                            <div className="fixed inset-0 overflow-y-auto w-full">
                                <div className="flex min-h-full items-center justify-center p-4 text-center">
                                <Transition.Child
                                    as={Fragment}
                                    enter="ease-out duration-300"
                                    enterFrom="opacity-0 scale-95"
                                    enterTo="opacity-100 scale-100"
                                    leave="ease-in duration-200"
                                    leaveFrom="opacity-100 scale-100"
                                    leaveTo="opacity-0 scale-95"
                                >
                                    <Dialog.Panel className="w-2/3 wtransform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle transition-all">
                                        <Dialog.Title
                                            as="h5"
                                            className="text-2xl font-bold leading-6 text-gray-900 text-center pt-2"
                                        >
                                            Antes de continuar...
                                        </Dialog.Title>
                                        
                                        <div className="pt-2">
                                            <h2 className="text-center text-xl font-semibold  pt-4">¿Por que el binario es la base de la programación?</h2>
                                        </div>
                                        <div className="justify-center">
                                            <div className="grid content-center grid-cols-2 mx-2 pt-12">
                                                <div className="p-2 text-right">
                                                    <button className="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded focus:bg-green-400">Example for 1 answer</button>
                                                </div>
                                                <div className="p-2 text-left">
                                                    <button className="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded focus:bg-green-400">Example for 1 answer</button>
                                                </div>
                                                <div className="p-2 text-right">
                                                    <button className="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded focus:bg-green-400">Example for 1 answer</button>
                                                </div>
                                                <div className="p-2 text-left">
                                                    <button className="bg-gray-700 hover:bg-gray-900 text-white font-bold py-2 px-4 rounded focus:bg-green-400">Example for 1 answer</button>
                                                </div>
                                            </div>
                                            <div className="p-2 flex justify-center">
                                                <button onClick={nextStep} className="bg-[#1A1C1F] text-white w-96 py-3 rounded-md hover:bg-[#2C3036] font-bold shadow-md">Vamos!</button>
                                            </div>
                                        </div>
                                    </Dialog.Panel>
                                </Transition.Child>
                                </div>
                            </div>
                            </Dialog>
                        </Transition>
                </div>
            </main>
        </>
    )
}

